### PR TITLE
[WIP] Enabling type hinting and updating mypy in tox

### LINKED ISSUE #44: Audit type hints and expose types via PEP561
## What is wrong?

The library currently uses type hints, however they may be able to be tightened up.

In addition, [PEP561](https://www.python.org/dev/peps/pep-0561/) allows us to expose type hints from this library to other libraries which use it.

## Definition of done?

* Update `mypy` to the latest stable released version.
* Update the `mypy` run in CI to the following.

```
mypy --follow-imports=silent --warn-unused-ignores --ignore-missing-imports --no-strict-optional --check-untyped-defs --disallow-incomplete-defs --disallow-untyped-defs --disallow-any-generics -p eth_keys`
```

* Usage of `type: ignore` (silencing the type checker) is minimized and there's a reasonable explanation for its usage 

* Update the `setup.py` to expose this data to other libraries as was done here: https://github.com/ethereum/eth-typing/pull/10

### Stretch goals

When this issue is done, stretch goals can be applied (and individually get funded) to tighten type support to qualify:

1. `mypy --strict --follow-imports=silent --ignore-missing-imports --no-strict-optional -p eth_keys`

Do what was done in https://github.com/ethereum/eth-typing/pull/10 to allow this data to be exposed when this library is installed as a package.

### PR DESCRIPTION
**Pull request by 6ug**
[WIP] My next step will be finding out type hinting annotation issues and fixing it manually (going to work on in couple of hours)

### What was wrong?
Fixes https://github.com/ethereum/eth-keys/issues/44

### How was it fixed?
Applying https://www.python.org/dev/peps/pep-0561/#id18

#### Cute Animal Picture

Cute animal picture

### CODE REVIEW

**Comment by pipermerriam** [comment]
@6ug I've rebased this branch onto master (which now uses circle ci) and added a single small commit.

One thing that needs to be done is to convert all of the comment based type hints for function signatures to be in the new format.  See 13c7aa8 for details.

**Comment by 6ug** [comment]
You were talking about this annotation, right @pipermerriam? 
```
(eth-keys) 🎩 ➜  eth-keys git:(PEP561) mypy --follow-imports=silent --warn-unused-ignores --ignore-missing-imports --no-strict-optional --check-untyped-defs --disallow-incomplete-defs --disallow-untyped-defs --disallow-any-generics -p eth_keys
eth_keys/datatypes.py:97: error: Incompatible return value type (got "bytes", expected "BaseECCBackend")
eth_keys/datatypes.py:101: error: Incompatible types in assignment (expression has type "BaseECCBackend", variable has type "bytes")
```

[+edited]
Oh! No I got that, you said comment based. Yes, on the way.

**Comment by pipermerriam** [comment]
Looks like this needs to be rebased and still has some CI errors.

**Comment by Bhargavasomu** [comment]
The work in this PR has been already taken care in #48, rendering this PR obsolete. Can be closed.

**Pull request closed without merging**
